[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/yahoo"
  to = "/.netlify/functions/yahoo"
  status = 200

[[redirects]]
  from = "/api/fred"
  to = "/.netlify/functions/fred"
  status = 200

[[redirects]]
  from = "/api/analysis"
  to = "/.netlify/functions/analysis"
  status = 200

[[redirects]]
  from = "/api/yahoo-quote"
  to = "/.netlify/functions/yahoo-quote"
  status = 200
